### ISSUE TITLE
No main method in OrionServer (& config parsing issues)

### ISSUE THREAD

**Issue by donny-stripe** [pinterest/orion#6]
I'm following the [Quick Start Guide](https://github.com/pinterest/orion/blob/master/docs/QuickStart.md) but I get an error when running `/opt/orion-server/scripts/run_orion.sh`:
```
Error: Main method not found in class com.pinterest.orion.server.OrionServer, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```
Looking at [OrionServer.java](https://github.com/pinterest/orion/blob/master/orion-server/src/main/java/com/pinterest/orion/server/OrionServer.java#L68) it's abstract with 1 unimplemented method and I don't see anything that extends it.

I tried making it non-abstract (commenting out the abstract method and the 1 invocation) and adding a main method:
```
public static void main(String[] args) throws Exception {
  new OrionServer().run(args);
}
```
and that runs, but I get an exception parsing config:
```
io.dropwizard.configuration.ConfigurationParsingException: conf/kafka-server.yaml has an error:
  * Unrecognized field at: plugins.actionConfigs.[0].endpointEnabled
    Did you mean?:
      - endpoint
      - enabled
      - configuration
      - class
      - key

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.pinterest.orion.server.OrionServer.main(OrionServer.java:70)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "endpointEnabled" (class com.pinterest.orion.core.configs.ActionConfig), not marked as ignorable (5 known properties: "class", "enabled", "endpoint", "configuration", "key"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.pinterest.orion.server.config.OrionConf["plugins"]->com.pinterest.orion.server.config.OrionPluginConfig["actionConfigs"]->java.util.ArrayList[0]->com.pinterest.orion.core.configs.ActionConfig["endpointEnabled"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2277)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
```
This is on a fresh install of ubuntu 20.04.

**Comment by ambud** [comment]
Hi @donny-stripe thanks for reporting this issue, I think this is related to a recent refactor. We will try to fix it this week.

**Comment by ambud** [comment]
We have fixed the issue, it should work/launch now.

**Comment by ambud** [comment]
@donny-stripe please feel free to open another ticket if you are still experiencing issues with the base setup.

**Comment by jcberseron** [comment]
Hello @ambud, i followed the "Quick Start Guide" and I got the same error when running /opt/orion-server/scripts/run_orion.sh: 

````
io.dropwizard.configuration.ConfigurationParsingException: /opt/orion-server/conf/kafka-server.yaml has an error:
  * Unrecognized field at: plugins.actionConfigs.[0].endpointEnabled
    Did you mean?:
      - endpoint
      - enabled
      - configuration
      - class
      - key

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.pinterest.orion.server.OrionServer.main(OrionServer.java:298)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "endpointEnabled" (class com.pinterest.orion.core.configs.ActionConfig), not marked as ignorable (5 known properties: "class", "enabled", "endpoint", "configuration", "key"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.pinterest.orion.server.config.OrionConf["plugins"]->com.pinterest.orion.server.config.OrionPluginConfig["actionConfigs"]->java.util.ArrayList[0]->com.pinterest.orion.core.configs.ActionConfig["endpointEnabled"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:258)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:47)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2277)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more

Thank you in advance for your help
